"""initial schema

Revision ID: cd48b8f3d8eb
Revises: 
Create Date: 2026-06-04 17:57:28.162791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd48b8f3d8eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_market',
    sa.Column('port', sa.String(length=8), nullable=False),
    sa.Column('market', sa.String(length=4), nullable=False),
    sa.Column('set_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('port')
    )
    op.create_table('case',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('ftv_scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=4), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('hourly_kw', sa.JSON(), nullable=False),
    sa.Column('smooth_sigma', sa.Float(), nullable=False),
    sa.Column('offset_h', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('saved_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'date', name='uq_ftv_scenario')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('dentrh', sa.JSON(), nullable=False),
    sa.Column('rt', sa.JSON(), nullable=False),
    sa.Column('distribution', sa.JSON(), nullable=False),
    sa.Column('mult96', sa.JSON(), nullable=False),
    sa.Column('rt_on96', sa.JSON(), nullable=False),
    sa.CheckConstraint("mode IN ('simulation','real')", name='ck_profile_mode'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_name'), 'profile', ['name'], unique=True)
    op.create_table('realio_config',
    sa.Column('market', sa.String(length=4), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('cookies', sa.JSON(), nullable=True),
    sa.Column('tags_read', sa.JSON(), nullable=False),
    sa.Column('tags_write', sa.JSON(), nullable=False),
    sa.Column('fve_control', sa.JSON(), nullable=False),
    sa.Column('poll_interval_sec', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('market')
    )
    op.create_table('ui_settings',
    sa.Column('port', sa.String(length=8), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('port', 'key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('last_login', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("role IN ('admin','obchodnik','trading','zakaznik')", name='ck_user_role'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('active_profile',
    sa.Column('port', sa.String(length=8), nullable=False),
    sa.Column('market', sa.String(length=4), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('set_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('port', 'market')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('auth_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.String(length=32), nullable=False),
    sa.Column('last_seen', sa.String(length=32), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_session_expires_at'), 'auth_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_session_token'), 'auth_session', ['token'], unique=True)
    op.create_index(op.f('ix_auth_session_user_id'), 'auth_session', ['user_id'], unique=False)
    op.create_table('auto_control_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(length=4), nullable=False),
    sa.Column('soc_pct', sa.Float(), nullable=True),
    sa.Column('batt_kw_setpoint', sa.Float(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('margin_check', sa.Boolean(), nullable=True),
    sa.Column('soc_terminal_ok', sa.Boolean(), nullable=True),
    sa.Column('grid_capacity_ok', sa.Boolean(), nullable=True),
    sa.Column('plan_available', sa.Boolean(), nullable=True),
    sa.Column('setpoint_clipped', sa.Boolean(), nullable=True),
    sa.Column('grid_kw_min', sa.Float(), nullable=True),
    sa.Column('grid_kw_max', sa.Float(), nullable=True),
    sa.Column('price_eur_mwh', sa.Float(), nullable=True),
    sa.Column('qty_kwh', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_control_event_profile_id'), 'auto_control_event', ['profile_id'], unique=False)
    op.create_index(op.f('ix_auto_control_event_ts'), 'auto_control_event', ['ts'], unique=False)
    op.create_table('load_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=4), nullable=False),
    sa.Column('weekday_kw', sa.JSON(), nullable=False),
    sa.Column('weekend_kw', sa.JSON(), nullable=False),
    sa.Column('imported_dates', sa.JSON(), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'market', name='uq_load_profile')
    )
    op.create_index(op.f('ix_load_profile_profile_id'), 'load_profile', ['profile_id'], unique=False)
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=4), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('step_min', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('mults', sa.JSON(), nullable=False),
    sa.Column('rt_mask', sa.JSON(), nullable=False),
    sa.Column('block_planned_discharge', sa.Boolean(), nullable=False),
    sa.Column('zco_bias_w', sa.Float(), nullable=False),
    sa.Column('rt_freedom', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'market', 'date', 'kind', 'step_min', name='uq_plan_per_day')
    )
    op.create_index('idx_plan_lookup', 'plan', ['market', 'profile_id', 'date'], unique=False)
    op.create_index(op.f('ix_plan_date'), 'plan', ['date'], unique=False)
    op.create_index(op.f('ix_plan_market'), 'plan', ['market'], unique=False)
    op.create_index(op.f('ix_plan_profile_id'), 'plan', ['profile_id'], unique=False)
    op.create_table('plan_override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=4), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('mult96', sa.JSON(), nullable=False),
    sa.Column('rt_on96', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'market', 'date', name='uq_plan_override')
    )
    op.create_index(op.f('ix_plan_override_profile_id'), 'plan_override', ['profile_id'], unique=False)
    op.create_table('user_profile_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_write', sa.Boolean(), nullable=False),
    sa.Column('can_write_hw', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.String(length=32), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'profile_id')
    )
    op.create_table('vdt_paper_trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=4), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('slot', sa.String(length=5), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('kwh', sa.Float(), nullable=False),
    sa.Column('price_eur_mwh', sa.Float(), nullable=False),
    sa.Column('dam_clearing_eur_mwh', sa.Float(), nullable=True),
    sa.Column('soc_before_pct', sa.Float(), nullable=True),
    sa.Column('soc_after_pct', sa.Float(), nullable=True),
    sa.Column('delta_profit_eur', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'date', 'slot', 'action', name='uq_vdt_paper_trade')
    )
    op.create_index('idx_vdt_lookup', 'vdt_paper_trade', ['market', 'profile_id', 'date'], unique=False)
    op.create_index(op.f('ix_vdt_paper_trade_date'), 'vdt_paper_trade', ['date'], unique=False)
    op.create_index(op.f('ix_vdt_paper_trade_profile_id'), 'vdt_paper_trade', ['profile_id'], unique=False)
    op.create_table('plan_slot',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('slot_idx', sa.Integer(), nullable=False),
    sa.Column('pv_kwh', sa.Float(), nullable=False),
    sa.Column('load_kwh', sa.Float(), nullable=False),
    sa.Column('price_eur', sa.Float(), nullable=False),
    sa.Column('batt_kw', sa.Float(), nullable=False),
    sa.Column('grid_kwh', sa.Float(), nullable=False),
    sa.Column('order_mwh', sa.Float(), nullable=False),
    sa.Column('curtail_kwh', sa.Float(), nullable=False),
    sa.Column('soc_pct', sa.Float(), nullable=False),
    sa.Column('soc_kwh', sa.Float(), nullable=False),
    sa.Column('charge_kw', sa.Float(), nullable=False),
    sa.Column('discharge_kw', sa.Float(), nullable=False),
    sa.Column('export_kwh', sa.Float(), nullable=False),
    sa.Column('import_kwh', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', 'slot_idx')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_slot')
    op.drop_index(op.f('ix_vdt_paper_trade_profile_id'), table_name='vdt_paper_trade')
    op.drop_index(op.f('ix_vdt_paper_trade_date'), table_name='vdt_paper_trade')
    op.drop_index('idx_vdt_lookup', table_name='vdt_paper_trade')
    op.drop_table('vdt_paper_trade')
    op.drop_table('user_profile_access')
    op.drop_index(op.f('ix_plan_override_profile_id'), table_name='plan_override')
    op.drop_table('plan_override')
    op.drop_index(op.f('ix_plan_profile_id'), table_name='plan')
    op.drop_index(op.f('ix_plan_market'), table_name='plan')
    op.drop_index(op.f('ix_plan_date'), table_name='plan')
    op.drop_index('idx_plan_lookup', table_name='plan')
    op.drop_table('plan')
    op.drop_index(op.f('ix_load_profile_profile_id'), table_name='load_profile')
    op.drop_table('load_profile')
    op.drop_index(op.f('ix_auto_control_event_ts'), table_name='auto_control_event')
    op.drop_index(op.f('ix_auto_control_event_profile_id'), table_name='auto_control_event')
    op.drop_table('auto_control_event')
    op.drop_index(op.f('ix_auth_session_user_id'), table_name='auth_session')
    op.drop_index(op.f('ix_auth_session_token'), table_name='auth_session')
    op.drop_index(op.f('ix_auth_session_expires_at'), table_name='auth_session')
    op.drop_table('auth_session')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('active_profile')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_table('user')
    op.drop_table('ui_settings')
    op.drop_table('realio_config')
    op.drop_index(op.f('ix_profile_name'), table_name='profile')
    op.drop_table('profile')
    op.drop_table('ftv_scenario')
    op.drop_table('case')
    op.drop_table('active_market')
    # ### end Alembic commands ###
